### ISSUE TITLE
Support opening Replica in read-only mode

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#479]
Lots of access to the Replica is only reading, not writing. SQLite can be quite a bit faster in that circumstance. Also, SQLite writes to the database itself when opened in read-write mode (https://github.com/GothenburgBitFactory/taskwarrior/issues/3418).

Let's allow opening a Replica in read-only mode.

**Comment by felixschurk** [comment]
Am I right in the understanding that following code opens the database?

 https://github.com/GothenburgBitFactory/taskchampion/blob/f4e1679105316a26be7928d7efeaeffa6966a8a7/taskchampion/src/storage/sqlite.rs#L80-L155

How is the connection process between taskwarrior and taskchampion for opening the database? Because for my understanding one could open all the `task report` commands the DB in read-only. But I do not really understand how the behavior is implemented.

**Comment by djmitche** [comment]
Yes, and in particular `Connection::open_with_flags` is the call to rusqlite.

To fix, I think we would add a boolean to StorageConfig::OnDisk, then set that value via the C++ bridge functions.

A possible tricky bit will be in Taskwarrior: _sometimes_ it writes during report commands, when it applies garbage collection. I think there's already a flag for that in the Command structure, so probably that could be handled correctly, but I haven't looked.

**Comment by djmitche** [comment]
...but of course, changing `StorageConfig` is a semver-breaking change, which would put us right onto 2.0.0! That's not the end of the world, but I'll think about whether there's another option.
